AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation stack to create an S3 bucket

Parameters:
  BucketName:
    Type: String
    Description: rajdevops

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
