stacks:
  s3-app:
    template: template/s3.yml
    region: ap-south-1
    base_name: s3-app-stack

  dynamo_db:
    template: template/DynamoDB.yml
    region: ap-south-1
    TableName: terraform-locks-dev
    PartitionKeyName: LockID
    PartitionKeyType: S
    BillingMode: PAY_PER_REQUEST

