name: Deploy Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::844099234941:role/github_action_role
          aws-region: ap-south-1
      - name: Install dependencies
        run: pip install boto3 pyyaml
      - name: Deploy production stack
        run: python deploy_stack.py
