name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::844099234941:role/github_action_role
          aws-region: ap-south-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file s3.yml \
            --stack-name app-deployment-stack \
            --capabilities CAPABILITY_NAMED_IAM

