name: PR Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::844099234941:role/github_action_role
          aws-region: ap-south-1

      - name: Install dependencies
        run: pip install boto3 cfn-lint

      - name: Lint CloudFormation
        run: cfn-lint s3.yml

      - name: Deploy PR stack
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          AWS_REGION: ap-south-1
        run: python manage_stack.py deploy
